CREATE TABLE S_Partner_ID
(
    P_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Nev VARCHAR (40) NOT NULL,
    Irszam VARCHAR (10) NOT NULL,
    Varos VARCHAR (40) NOT NULL,
    Utca VARCHAR (40) NOT NULL,
    Tel VARCHAR (20),
    Email VARCHAR (40) NOT NULL
);

